[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFCFA"  
secondaryBackgroundColor = "#FFFFFF" 
textColor = "#1F1F1F"
font = "sans serif"

[client]
toolbarMode = "viewer"

[server]
headless = true